# PR pipeline for the compute layer in Dev environment
stages:
  - stage: Terraform_PR
    displayName: PR pipeline
    dependsOn: []

    jobs:
    - job: Job_1
      displayName: Terraform test, format and plan

      pool:
        vmImage: ubuntu-latest
        
      steps:
      - task: TerraformTaskV3@3
        displayName: Terraform format
        inputs:
          provider: 'azurerm'
          command: 'custom'
          customCommand: 'fmt'
          workingDirectory: 'network_security'
          commandOptions: '--recursive'
          outputTo: 'console'
          environmentServiceNameAzureRM: $(terraformServiceConnection)

      - task: TerraformTaskV3@3
        displayName: Terraform init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: network_security
          backendServiceArm: $(terraformServiceConnection)
          backendAzureRmResourceGroupName: $(stateResourceGroup)
          backendAzureRmStorageAccountName: $(stateStorageAccount)
          backendAzureRmContainerName: $(stateContainer)
          backendAzureRmKey: $(stateStorageKey)

      - task: TerraformTaskV3@3
        displayName: Terraform plan
        env:
          TF_VAR_tenant_id: $(SUBSCRIPTION_ID)
        inputs:
          command: plan
          workingDirectory: network_security
          commandOptions: -var-file=$(System.DefaultWorkingDirectory)/network_security/$(environment).tfvars
          environmentServiceNameAzureRM: $(terraformServiceConnection)